language: objective-c
osx_image: xcode7.3

branches:
  only:
    - develop
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
  - ACTION=test PLATFORM=iOS DESTINATION='platform=iOS Simulator,name=iPhone 6S,OS=9.0'
  - ACTION=test PLATFORM=iOS DESTINATION='platform=iOS Simulator,name=iPhone 6S,OS=10.0'

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true

script:
  - set -o pipefail
  - xcodebuild -workspace Gigsterous.xcworkspace -scheme Gigsterous -destination "$DESTINATION" $ACTION | xcpretty -c
  - swiftlint