language: objective-c
osx_image: xcode7.3
xcode_workspace: Gigsterous.xcworkspace
xcode_scheme: Gigsterous
xcode_sdk: iphonesimulator9.3
podfile: Podfile

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2 #cocoapods 1.0.0 requirement not yet supported ootb by travis
  - gem install cocoapods
  - gem install xcpretty -N
script:
  - set -o pipefail
  #- xcodebuild -workspace Gigsterous.xcworkspace -scheme "Gigsterous" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
  - xcodebuild test -workspace Gigsterous.xcworkspace -scheme Gigsterous -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - pod lib lint --quick