language: objective-c
osx_image: xcode8

branches:
  only:
    - develop
    - master

before_script:
  - export LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods --pre
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  - pod update Moya
  - gem update fastlane --no-ri --no-rdoc --no-document

script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then fastlane test fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then fastlane beta fi
  - swiftlint

after_success:
  - bash <(curl -s https://codecov.io/bash)
